# Generated by Django 4.2.7 on 2023-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Plutôt que de supprimer un article, il est préférable de le marquer hors stock.', verbose_name='en stock'),
        ),
    ]
