# Generated by Django 4.2.7 on 2023-11-16 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_image'),
        ('inventory', '0002_item_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'get_latest_by': 'mod_date', 'verbose_name': 'objet'},
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product', verbose_name='produit'),
        ),
    ]
