# Generated by Django 4.2.7 on 2024-01-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_options_alter_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de sortie de stock'),
        ),
        migrations.AddField(
            model_name='item',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text="Spécifications de l'objet. Elles seront validées par le schéma de spécifications d'objets du type de produit sélectionné.", max_length=1024, verbose_name='spécifications'),
        ),
    ]
