# Generated by Django 4.2.7 on 2023-11-08 21:25

import catalog.models
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("model", "Category")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="childs",
                to="catalog.category",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="specs_schema",
            field=models.JSONField(
                default=catalog.models.make_default_object_schema,
                help_text="Schéma des spécifications propres à cette catégorie de produits, au format JSONSchema 2020-12.",
                max_length=1024,
                validators=[common.validators.JSONSchemaValidator()],
                verbose_name="schéma de spécifications",
            ),
        ),
    ]
