# Generated by Django 4.2.7 on 2023-11-09 17:24

import common.utils
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_parent_alter_category_specs_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkind',
            name='name_format',
            field=models.CharField(default='oui', help_text='Gabarit Python spécifiant le nom des produits.', max_length=128, verbose_name='format du nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'productkind__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='catalog.category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='specs_schema',
            field=models.JSONField(default=common.utils.make_default_object_schema, encoder=common.utils.JSONSetEncoder, help_text='Schéma des spécifications propres à cette catégorie de produits, au format JSONSchema 2020-12.', max_length=1024, validators=[common.validators.JSONSchemaValidator()], verbose_name='schéma de spécifications'),
        ),
    ]
