# Generated by Django 4.2.7 on 2023-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productkind_name_format_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text="Image d'illustration du produit.", upload_to='products', verbose_name='image'),
        ),
    ]
