# Generated by Django 4.2.7 on 2024-01-24 20:00

import common.utils
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkind',
            name='item_name_format',
            field=models.CharField(default='{PRODUCT}', help_text='Gabarit Python spécifiant le nom des objets. {PRODUCT} cible le nom des produits.', max_length=128, verbose_name='format du nom des objets'),
        ),
        migrations.AddField(
            model_name='productkind',
            name='item_specs_schema',
            field=models.JSONField(default=common.utils.make_default_object_schema, encoder=common.utils.JSONSetEncoder, help_text="Schéma des spécifications propres aux instances d'objets liées à cette catégorie de produits, au format JSONSchema 2020-12.", max_length=1024, validators=[common.validators.JSONSchemaValidator()], verbose_name='schéma de spécifications des objets'),
        ),
    ]
